species: human

references:
  human:
    genome: "/path/to/hg38.fa"
    chrom_sizes: "/path/to/hg38.chrom.sizes"
    black_list: "/path/to/hg38-blacklist.v2.bed"
    bt2_index: "/path/to/hg38"
    name: "hg38"
    gsize: "2.7e9"
  mouse:
    genome: "/path/to/mm10.fa"
    chrom_sizes: "/path/to/mm10.chrom.sizes"
    black_list: "/path/to/mm10-blacklist.v2.bed"
    bt2_index: "/path/to/mm10"
    name: "mm10"
    gsize: "1.87e9"
  rat:
    genome: "/path/to/rn6.fa"
    chrom_sizes: "/path/to/rn6.chrom.sizes"
    black_list: "/path/to/rn6-blacklist.bed"
    bt2_index: "/path/to/rn6"
    name: "rn6"
    gsize: "2.53e9"

chip_controls:
  - id: Input_control_rep1
    fastq:
      - data/raw/Input_control_rep1_R1.fastq.gz
      - data/raw/Input_control_rep1_R2.fastq.gz
  - id: Input_control_rep2
    fastq:
      - data/raw/Input_control_rep2_R1.fastq.gz
      - data/raw/Input_control_rep2_R2.fastq.gz
  - id: Input_treated_rep1
    fastq:
      - data/raw/Input_treated_rep1_R1.fastq.gz
      - data/raw/Input_treated_rep1_R2.fastq.gz
  - id: Input_treated_rep2
    fastq:
      - data/raw/Input_treated_rep2_R1.fastq.gz
      - data/raw/Input_treated_rep2_R2.fastq.gz

chip_samples:
  - id: H3K27ac_control_rep1
    fastq:
      - data/raw/H3K27ac_control_rep1_R1.fastq.gz
      - data/raw/H3K27ac_control_rep1_R2.fastq.gz
    control: Input_control_rep1
    condition: control
    replicate: 1
    factor: H3K27ac
    tissue: example
  - id: H3K27ac_control_rep2
    fastq:
      - data/raw/H3K27ac_control_rep2_R1.fastq.gz
      - data/raw/H3K27ac_control_rep2_R2.fastq.gz
    control: Input_control_rep2
    condition: control
    replicate: 2
    factor: H3K27ac
    tissue: example
  - id: H3K27ac_treated_rep1
    fastq:
      - data/raw/H3K27ac_treated_rep1_R1.fastq.gz
      - data/raw/H3K27ac_treated_rep1_R2.fastq.gz
    control: Input_treated_rep1
    condition: treated
    replicate: 1
    factor: H3K27ac
    tissue: example
  - id: H3K27ac_treated_rep2
    fastq:
      - data/raw/H3K27ac_treated_rep2_R1.fastq.gz
      - data/raw/H3K27ac_treated_rep2_R2.fastq.gz
    control: Input_treated_rep2
    condition: treated
    replicate: 2
    factor: H3K27ac
    tissue: example
