species: human

references:
  human:
    genome: "/path/to/hg38.fa"
    chrom_sizes: "/path/to/hg38.chrom.sizes"
    black_list: "/path/to/hg38-blacklist.v2.bed"
    bt2_index: "/path/to/hg38"
    name: "hg38"
    gsize: "2.7e9"

contamination:
  fastq_screen_conf: "config/fastq_screen.conf.example"
  subset: 100000

chip_controls:
  - id: Input_control_rep1
    fastq:
      - data/raw/Input_control_rep1_R1.fastq.gz
      - data/raw/Input_control_rep1_R2.fastq.gz
  - id: Input_control_rep2
    fastq:
      - data/raw/Input_control_rep2_R1.fastq.gz
      - data/raw/Input_control_rep2_R2.fastq.gz
  - id: Input_treated_rep1
    fastq:
      - data/raw/Input_treated_rep1_R1.fastq.gz
      - data/raw/Input_treated_rep1_R2.fastq.gz
  - id: Input_treated_rep2
    fastq:
      - data/raw/Input_treated_rep2_R1.fastq.gz
      - data/raw/Input_treated_rep2_R2.fastq.gz

chip_samples:
  - id: H3K27ac_control_rep1
    fastq:
      - data/raw/H3K27ac_control_rep1_R1.fastq.gz
      - data/raw/H3K27ac_control_rep1_R2.fastq.gz
    control: Input_control_rep1
    condition: control
    replicate: 1
    factor: H3K27ac
    tissue: example
    mark_type: histone  # 'histone' -> MACS2 broad peaks, 'tf' -> narrow peaks
  - id: H3K27ac_control_rep2
    fastq:
      - data/raw/H3K27ac_control_rep2_R1.fastq.gz
      - data/raw/H3K27ac_control_rep2_R2.fastq.gz
    control: Input_control_rep2
    condition: control
    replicate: 2
    factor: H3K27ac
    tissue: example
    mark_type: histone  # 'histone' -> MACS2 broad peaks, 'tf' -> narrow peaks
  - id: H3K27ac_treated_rep1
    fastq:
      - data/raw/H3K27ac_treated_rep1_R1.fastq.gz
      - data/raw/H3K27ac_treated_rep1_R2.fastq.gz
    control: Input_treated_rep1
    condition: treated
    replicate: 1
    factor: H3K27ac
    tissue: example
    mark_type: histone  # 'histone' -> MACS2 broad peaks, 'tf' -> narrow peaks
  - id: H3K27ac_treated_rep2
    fastq:
      - data/raw/H3K27ac_treated_rep2_R1.fastq.gz
      - data/raw/H3K27ac_treated_rep2_R2.fastq.gz
    control: Input_treated_rep2
    condition: treated
    replicate: 2
    factor: H3K27ac
    tissue: example
    mark_type: histone  # 'histone' -> MACS2 broad peaks, 'tf' -> narrow peaks
