#!/usr/bin/env Rscript
# Open-source motif enrichment for ChIP-seq consensus peaks.
#
# Replaces the previous HOMER `findMotifsGenome.pl` step with monaLisa + JASPAR,
# both of which are permissively licensed and redistributable. Peaks are scored
# against the vertebrate JASPAR core motifs using a composition-matched background
# generated by monaLisa (`background = "genNB"`), so no species-specific
# precomputed background is required (works for human, mouse, and rat).
#
# Usage: Rscript motif_enrichment.R consensus_peaks.bed genome.fa outdir

args <- commandArgs(trailingOnly = TRUE)
if (length(args) < 3) {
    stop("Usage: Rscript motif_enrichment.R consensus_peaks.bed genome.fa outdir")
}

peaks_bed <- args[1]
genome_fa <- args[2]
outdir <- args[3]

if (!dir.exists(outdir)) dir.create(outdir, recursive = TRUE)

suppressPackageStartupMessages({
    library(monaLisa)
    library(JASPAR2020)
    library(TFBSTools)
    library(GenomicRanges)
    library(rtracklayer)
    library(Rsamtools)
    library(Biostrings)
    library(SummarizedExperiment)
    library(readr)
    library(dplyr)
    library(ggplot2)
})

peak_width <- 200

# --- Load consensus peaks and center them to a fixed width ---
peaks <- import(peaks_bed)
if (length(peaks) == 0) stop("No peaks found in ", peaks_bed)
peaks <- resize(peaks, width = peak_width, fix = "center")

# --- Genome sequence access (FASTA + .fai index) ---
if (!file.exists(paste0(genome_fa, ".fai"))) {
    indexFa(genome_fa)
}
genome <- FaFile(genome_fa)
gi <- seqinfo(genome)

# Keep only peaks on contigs present in the genome, then clamp to contig bounds
common <- intersect(seqlevels(peaks), seqlevels(gi))
if (length(common) == 0) {
    stop("No overlapping sequence names between peaks and genome FASTA. ",
         "Check that the peak set and genome use the same assembly/naming.")
}
peaks <- keepSeqlevels(peaks, common, pruning.mode = "coarse")
seqlengths(peaks) <- seqlengths(gi)[common]
peaks <- trim(peaks)
peaks <- peaks[width(peaks) >= 20]
if (length(peaks) == 0) stop("No peaks remain after trimming to genome bounds")

seqs <- getSeq(genome, peaks)
names(seqs) <- paste0("peak_", seq_along(seqs))

# --- JASPAR vertebrate core motifs (CC0 / open) ---
pwms <- getMatrixSet(JASPAR2020, list(matrixtype = "PWM", tax_group = "vertebrates"))

# --- Enrichment vs. a composition-matched background generated by monaLisa ---
bins <- factor(rep("peaks", length(seqs)))
se <- calcBinnedMotifEnrR(
    seqs = seqs,
    bins = bins,
    pwmL = pwms,
    background = "genNB",
    verbose = TRUE
)

# --- Assemble the full results table ---
motif_name <- rowData(se)$motif.name
if (is.null(motif_name)) {
    id2name <- setNames(TFBSTools::name(pwms), names(pwms))
    motif_name <- unname(id2name[rownames(se)])
}
neglog10p <- assay(se, "negLog10P")[, 1]
res <- tibble(
    Motif.Name = motif_name,
    Motif.ID = rownames(se),
    log2enr = assay(se, "log2enr")[, 1],
    negLog10P = neglog10p,
    negLog10Padj = assay(se, "negLog10Padj")[, 1],
    P.value = 10^(-neglog10p)
) %>%
    arrange(desc(negLog10P))

write_tsv(res, file.path(outdir, "motif_enrichment.tsv"))

# --- Top-motif summary (CSV + plot), preserving prior output file names ---
top_motifs <- res %>%
    filter(is.finite(negLog10P)) %>%
    slice_head(n = 20)

write_csv(top_motifs, file.path(outdir, "motif_summary.csv"))

pdf(file.path(outdir, "motif_summary.pdf"), width = 10, height = 8)
print(
    ggplot(top_motifs, aes(x = reorder(Motif.Name, negLog10P), y = negLog10P)) +
        geom_col(fill = "steelblue") +
        coord_flip() +
        theme_minimal() +
        labs(title = "Top enriched motifs (monaLisa / JASPAR)",
             x = "Motif", y = "-log10(P-value)")
)
dev.off()
